language: node_js
node_js: 
    - "10"
dist: trusty
env: 
    - NODE_ENV=dev
cache: 
    directories:
        - node_modules
before_install: 
    - cd 3-layers-ts
install:
    - yarn install
test: 
    - yarn test